// Code generated by MockGen. DO NOT EDIT.
// Source: config_source_factory_strategy.go

// Package servlet is a generated GoMock package.
package servlet

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockConfigSourceFactoryStrategy is a mock of ConfigSourceFactoryStrategy interface
type MockConfigSourceFactoryStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockConfigSourceFactoryStrategyMockRecorder
}

// MockConfigSourceFactoryStrategyMockRecorder is the mock recorder for MockConfigSourceFactoryStrategy
type MockConfigSourceFactoryStrategyMockRecorder struct {
	mock *MockConfigSourceFactoryStrategy
}

// NewMockConfigSourceFactoryStrategy creates a new mock instance
func NewMockConfigSourceFactoryStrategy(ctrl *gomock.Controller) *MockConfigSourceFactoryStrategy {
	mock := &MockConfigSourceFactoryStrategy{ctrl: ctrl}
	mock.recorder = &MockConfigSourceFactoryStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfigSourceFactoryStrategy) EXPECT() *MockConfigSourceFactoryStrategyMockRecorder {
	return m.recorder
}

// Accept mocks base method
func (m *MockConfigSourceFactoryStrategy) Accept(sourceType string, args ...interface{}) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{sourceType}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Accept", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept
func (mr *MockConfigSourceFactoryStrategyMockRecorder) Accept(sourceType interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sourceType}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockConfigSourceFactoryStrategy)(nil).Accept), varargs...)
}

// AcceptConfig mocks base method
func (m *MockConfigSourceFactoryStrategy) AcceptConfig(conf ConfigPartial) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptConfig", conf)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcceptConfig indicates an expected call of AcceptConfig
func (mr *MockConfigSourceFactoryStrategyMockRecorder) AcceptConfig(conf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptConfig", reflect.TypeOf((*MockConfigSourceFactoryStrategy)(nil).AcceptConfig), conf)
}

// Create mocks base method
func (m *MockConfigSourceFactoryStrategy) Create(args ...interface{}) (ConfigSource, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(ConfigSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockConfigSourceFactoryStrategyMockRecorder) Create(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigSourceFactoryStrategy)(nil).Create), args...)
}

// CreateConfig mocks base method
func (m *MockConfigSourceFactoryStrategy) CreateConfig(conf ConfigPartial) (ConfigSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", conf)
	ret0, _ := ret[0].(ConfigSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfig indicates an expected call of CreateConfig
func (mr *MockConfigSourceFactoryStrategyMockRecorder) CreateConfig(conf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockConfigSourceFactoryStrategy)(nil).CreateConfig), conf)
}
