// Code generated by MockGen. DO NOT EDIT.
// Source: application_parameters.go

// Package servlet is a generated GoMock package.
package servlet

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockApplicationParameters is a mock of ApplicationParameters interface
type MockApplicationParameters struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationParametersMockRecorder
}

// MockApplicationParametersMockRecorder is the mock recorder for MockApplicationParameters
type MockApplicationParametersMockRecorder struct {
	mock *MockApplicationParameters
}

// NewMockApplicationParameters creates a new mock instance
func NewMockApplicationParameters(ctrl *gomock.Controller) *MockApplicationParameters {
	mock := &MockApplicationParameters{ctrl: ctrl}
	mock.recorder = &MockApplicationParametersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApplicationParameters) EXPECT() *MockApplicationParametersMockRecorder {
	return m.recorder
}

// GetEngineID mocks base method
func (m *MockApplicationParameters) GetEngineID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngineID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEngineID indicates an expected call of GetEngineID
func (mr *MockApplicationParametersMockRecorder) GetEngineID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngineID", reflect.TypeOf((*MockApplicationParameters)(nil).GetEngineID))
}

// SetEngineID mocks base method
func (m *MockApplicationParameters) SetEngineID(ID string) ApplicationParameters {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEngineID", ID)
	ret0, _ := ret[0].(ApplicationParameters)
	return ret0
}

// SetEngineID indicates an expected call of SetEngineID
func (mr *MockApplicationParametersMockRecorder) SetEngineID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEngineID", reflect.TypeOf((*MockApplicationParameters)(nil).SetEngineID), ID)
}
