// Code generated by MockGen. DO NOT EDIT.
// Source: log/formatter_factory_strategy.go

// Package log is a generated GoMock package.
package log

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFormatterFactoryStrategy is a mock of FormatterFactoryStrategy interface
type MockFormatterFactoryStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterFactoryStrategyMockRecorder
}

// MockFormatterFactoryStrategyMockRecorder is the mock recorder for MockFormatterFactoryStrategy
type MockFormatterFactoryStrategyMockRecorder struct {
	mock *MockFormatterFactoryStrategy
}

// NewMockFormatterFactoryStrategy creates a new mock instance
func NewMockFormatterFactoryStrategy(ctrl *gomock.Controller) *MockFormatterFactoryStrategy {
	mock := &MockFormatterFactoryStrategy{ctrl: ctrl}
	mock.recorder = &MockFormatterFactoryStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFormatterFactoryStrategy) EXPECT() *MockFormatterFactoryStrategyMockRecorder {
	return m.recorder
}

// Accept mocks base method
func (m *MockFormatterFactoryStrategy) Accept(format string, args ...interface{}) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Accept", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept
func (mr *MockFormatterFactoryStrategyMockRecorder) Accept(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockFormatterFactoryStrategy)(nil).Accept), varargs...)
}

// Create mocks base method
func (m *MockFormatterFactoryStrategy) Create(args ...interface{}) (Formatter, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(Formatter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockFormatterFactoryStrategyMockRecorder) Create(args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFormatterFactoryStrategy)(nil).Create), args...)
}
